stages:
  - test
  - build
  - deploy

variables:
  DOCKER_DRIVER: overlay
  docker_image_name: "docker.zeroq.cl/whatsapp-notifications"

build:
  image: docker:stable
  stage: build
  services:
    - docker:dind
  script:
    - docker build --rm -f Dockerfile --build-arg git_tag=${CI_COMMIT_TAG} -t ${docker_image_name}:${CI_COMMIT_TAG} .
    - docker push ${docker_image_name}:${CI_COMMIT_TAG}
  only:
    - tags

deploy:
  image: dtzar/helm-kubectl
  stage: deploy
  script:
    - sed -i "s#__TAG__#${CI_COMMIT_TAG}#" mandatory.yaml
    - sed -i "s#__DOCKER_IMAGE__#${docker_image_name}#" mandatory.yaml
    - kubectl apply -f mandatory.yaml --namespace=prod-services --kubeconfig=kubeconfig
  only:
    - tags
