version: '3.7'
services:

  main:
    build:
      context: ./sample_apps/go
      dockerfile: ./Dockerfile
    # `command` overrides the default CMD
    command:
      - air
    #command: # for integration testing
      #- go
      #- test
    env_file:
      - .env
    ports:
      - "127.0.0.1:${HOST_PORT}:${CONTAINER_PORT}/tcp"
    volumes:
      - ./:/app # mounts app from host for hot-reloading
      - gomodules:/go/pkg/mod
        #links:
        #- mongo
        #- postgres
        #- redis
        #- rabbit
        #depends_on:
        #- mongo
        #- postgres
        #- redis
        #- rabbit

  node:
    build:
      context: ./sample_apps/node
      dockerfile: ./.Dockerfile
      # `command` overrides the default CMD
    command: yarn run start
    # yarn run test:integration
    env_file:
      - .env
    ports:
      - "127.0.0.1:${HOST_PORT}:${CONTAINER_PORT}/tcp"
    volumes:
      - ./:/usr/src/app # mounts app from host for hot-reloading
      - nodemodules:/usr/src/app/node_modules
    links:
      - mongo
      - postgres
      - redis
      - rabbit
    depends_on:
      - mongo
      - postgres
      - redis
      - rabbit


  mongo:
    image: mongo:3.6
    env_file:
      - .mongo/.env
        #volumes:
        #- mongodb_data_container:/data/db

  postgres:
    image: postgres:9.6
    hostname: postgres
    env_file:
      - .postgres/.env
    volumes:
      - .postgres/docker-entrypoint-initdb.d/:/docker-entrypoint-initdb.d/

  redis:
    image: redis:6-alpine
    #env_file:
      #- .redis/.env
      #volumes:
      #- .redis/redis.conf:/usr/local/etc/redis/redis.conf

  rabbit:
    image: rabbitmq:3.8
    hostname: "rabbit"
    env_file:
      - ./.rabbitmq/.env
    volumes:
      - ./.rabbitmq/definitions.json:/etc/rabbitmq/definitions.json
      - ./.rabbitmq/rabbitmq-isolated.conf:/etc/rabbitmq/rabbitmq.config
      - ./.rabbitmq/logs/:/var/log/rabbitmq/

volumes:
  nodemodules: {}
  gomodules: {}
  #mongodb_data_container:
