version: '3.7'
services:

  main:
    build:
      context: ./
      dockerfile: local.Dockerfile
    command: npm run start # npm run test:integration on CI
    env_file:
      - .env
      - .postgres/.env
    ports:
      - "127.0.0.1:${DOCKER_HOST_PORT}:${DOCKER_CONTAINER_PORT}/tcp"
    volumes:
      - ./:/usr/src/app # mounts app from host for hot-reloading
      - nodemodules:/usr/src/app/node_modules
    links:
      - mongo
    depends_on:
      - mongo
      - postgres

  mongo:
    image: mongo:3.6
    env_file:
      - .env
        #volumes:
        #- mongodb_data_container:/data/db

  postgres:
    image: postgres:9.6
    hostname: postgres
    env_file:
      - .postgres/.env
    volumes:
      - .postgres/docker-entrypoint-initdb.d/:/docker-entrypoint-initdb.d/

  redis:
    image: redis:6-alpine
    env_file:
      - .env

  rabbit:
    image: rabbitmq:3.8
    env_file:
      - .env
    volumes:
      - ./.rabbitmq/definitions.json:/etc/rabbitmq/definitions.json

volumes:
  nodemodules: {}
  #mongodb_data_container:
