version: '3.7'
services:

  main:
    build:
      context: ./
      dockerfile: ./.docker/Dockerfile
    # `command` overrides the default CMD
    command: yarn run start # npm run test:integration on CI
    env_file:
      - .env
    ports:
      - "127.0.0.1:${DOCKER_HOST_PORT}:${DOCKER_CONTAINER_PORT}/tcp"
    volumes:
      - ./:/usr/src/app # mounts app from host for hot-reloading
      - nodemodules:/usr/src/app/node_modules
    links:
      - rabbit
      - mongo
    depends_on:
      - rabbit
      - mongo

  rabbit:
    image: rabbitmq:3.8
    hostname: "rabbit"
    env_file:
      - ./.rabbitmq/.env
    volumes:
      - ./.rabbitmq/definitions.json:/etc/rabbitmq/definitions.json

  producer:
    image: federico.com/rabbit-producer:latest
    env_file:
      - ./.rabbitmq/.env

  mongo:
    image: mongo:3.6
    env_file:
      - .mongo/.env
        #volumes:
        #- mongodb_data_container:/data/db

volumes:
  nodemodules: {}
  #mongodb_data_container:
